---
- name: Verify
  hosts: all
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: YADM
      block:
        - name: Register YADM version
          command: 'yadm --version'
          register: yadm_version

        - name: Verify that YADM is running
          assert:
            that: yadm_version.rc == 0

    - name: My dotfiles
      block:
        - name: Register an attempt to init a new repo that must fail
          command: yadm init
          changed_when: false
          ignore_errors: yes
          register: yadm_init_attempt

        - name: Verify that my dotfiles repo were already initialized
          assert:
            that:
              - 'yadm_init_attempt.rc == 1'
                # ubuntu and arch store this error differently, that's why I'm concatenating those two lists below
              - '"ERROR: Git repo already exists." in (yadm_init_attempt.stdout + yadm_init_attempt.stderr)'
